// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: gogorpc.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoGoPBRpcRequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq           uint64 `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	RpcMethodId   uint32 `protobuf:"varint,2,opt,name=RpcMethodId,proto3" json:"RpcMethodId,omitempty"`
	ServiceMethod string `protobuf:"bytes,3,opt,name=ServiceMethod,proto3" json:"ServiceMethod,omitempty"`
	NoReply       bool   `protobuf:"varint,4,opt,name=NoReply,proto3" json:"NoReply,omitempty"`
	InParam       []byte `protobuf:"bytes,5,opt,name=InParam,proto3" json:"InParam,omitempty"`
}

func (x *GoGoPBRpcRequestData) Reset() {
	*x = GoGoPBRpcRequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogorpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoGoPBRpcRequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoGoPBRpcRequestData) ProtoMessage() {}

func (x *GoGoPBRpcRequestData) ProtoReflect() protoreflect.Message {
	mi := &file_gogorpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoGoPBRpcRequestData.ProtoReflect.Descriptor instead.
func (*GoGoPBRpcRequestData) Descriptor() ([]byte, []int) {
	return file_gogorpc_proto_rawDescGZIP(), []int{0}
}

func (x *GoGoPBRpcRequestData) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GoGoPBRpcRequestData) GetRpcMethodId() uint32 {
	if x != nil {
		return x.RpcMethodId
	}
	return 0
}

func (x *GoGoPBRpcRequestData) GetServiceMethod() string {
	if x != nil {
		return x.ServiceMethod
	}
	return ""
}

func (x *GoGoPBRpcRequestData) GetNoReply() bool {
	if x != nil {
		return x.NoReply
	}
	return false
}

func (x *GoGoPBRpcRequestData) GetInParam() []byte {
	if x != nil {
		return x.InParam
	}
	return nil
}

type GoGoPBRpcResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq   uint64 `protobuf:"varint,1,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Reply []byte `protobuf:"bytes,3,opt,name=Reply,proto3" json:"Reply,omitempty"`
}

func (x *GoGoPBRpcResponseData) Reset() {
	*x = GoGoPBRpcResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gogorpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoGoPBRpcResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoGoPBRpcResponseData) ProtoMessage() {}

func (x *GoGoPBRpcResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_gogorpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoGoPBRpcResponseData.ProtoReflect.Descriptor instead.
func (*GoGoPBRpcResponseData) Descriptor() ([]byte, []int) {
	return file_gogorpc_proto_rawDescGZIP(), []int{1}
}

func (x *GoGoPBRpcResponseData) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GoGoPBRpcResponseData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GoGoPBRpcResponseData) GetReply() []byte {
	if x != nil {
		return x.Reply
	}
	return nil
}

var File_gogorpc_proto protoreflect.FileDescriptor

var file_gogorpc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x6f, 0x67, 0x6f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x72, 0x70, 0x63, 0x22, 0xa4, 0x01, 0x0a, 0x14, 0x47, 0x6f, 0x47, 0x6f, 0x50, 0x42, 0x52,
	0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a,
	0x03, 0x53, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12,
	0x20, 0x0a, 0x0b, 0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49,
	0x64, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x4e, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x55, 0x0a, 0x15, 0x47,
	0x6f, 0x47, 0x6f, 0x50, 0x42, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_gogorpc_proto_rawDescOnce sync.Once
	file_gogorpc_proto_rawDescData = file_gogorpc_proto_rawDesc
)

func file_gogorpc_proto_rawDescGZIP() []byte {
	file_gogorpc_proto_rawDescOnce.Do(func() {
		file_gogorpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_gogorpc_proto_rawDescData)
	})
	return file_gogorpc_proto_rawDescData
}

var file_gogorpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gogorpc_proto_goTypes = []interface{}{
	(*GoGoPBRpcRequestData)(nil),  // 0: rpc.GoGoPBRpcRequestData
	(*GoGoPBRpcResponseData)(nil), // 1: rpc.GoGoPBRpcResponseData
}
var file_gogorpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gogorpc_proto_init() }
func file_gogorpc_proto_init() {
	if File_gogorpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gogorpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoGoPBRpcRequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gogorpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoGoPBRpcResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gogorpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gogorpc_proto_goTypes,
		DependencyIndexes: file_gogorpc_proto_depIdxs,
		MessageInfos:      file_gogorpc_proto_msgTypes,
	}.Build()
	File_gogorpc_proto = out.File
	file_gogorpc_proto_rawDesc = nil
	file_gogorpc_proto_goTypes = nil
	file_gogorpc_proto_depIdxs = nil
}
